### ISSUE TITLE
Especificaciones incompletas

### ISSUE THREAD

**Issue by antoniojosesanchez** [DavidAntunezPerez/RestaurAPP#1]
- No se especifica en el `README.md` los objetivos del proyecto.
- No se especifica en el `README.md` el nombre de los desarrolladores y las tecnologías a utilizar.
- No se especifican qué otras tecnologías que se van a emplear (Firebase, Realtime, Firestore, Cloud, Picasso, Glide, Retrofit, etc.).
- No se especifica tipo de base de datos: ¿Relacional o No-SQL? ¿Vais a utilizar Room o Firebase? ¿Cuál es el diseño de la base de datos?

**Comment by dantudev** [comment]
🔧: Agregada información restante en el README.md
