### ISSUE TITLE
Acceso al informe en PowerBI

### ISSUE THREAD

**Issue by josedavid-quero** [DavidAntunezPerez/RestaurAPP#3]
En el documento no se indica ningún tipo de información que se vaya a visualizar en el informe ni cómo se va a acceder al mismo.

**Comment by AleCueto** [comment]
Buenas Jose David, nuestra idea es utilizar la información que saquemos usando python, (lista de comandas, platos, mesas...) para hacer manualmente el informe, esta eso bien? si es así lo especificaremos en el readme

**Comment by josedavid-quero** [comment]
Indicad, además, que se subirá al repositorio del proyecto y también se publicará en Power BI, compartiéndolo con la dirección de correo educativa del profesor.
jquesan535@m.educaand.es <-- esto no lo pongáis en la documentación

**Comment by AleCueto** [comment]
Perfecto Jose David, ya está modificado en el readme indicándolo.
